name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        id: read-nvmrc
        run: echo ::set-output name=node-version::$(cat .nvmrc)

      - name: Install node ${{ steps.read-nvmrc.outputs.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.read-nvmrc.outputs.node-version }}'

      - name: Install node dependencies
        run: npm ci

      - name: Build
        run: npm run build --prod

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages
          cname: roger.vanpeerdevelopment.be
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: dist